### PR TITLE
blog post: lts19 release and nightly to ghc9.2

### PR DESCRIPTION
**Pull request by juhp**
I think we can wait for the Nightly rebase to 9.2 before publishing this.

### CODE REVIEW

**Comment by juhp** [comment]
I would welcome any suggestions on possible improvements.

Maybe it is better to prefix the filename with the date?

**Comment by snoyberg** [comment]
LGTM. I'd recommend merging as it is now, we don't usually include dates in the filename.

**Review by bergmark — APPROVED** [review]

**Comment by juhp** [comment]
Okay, cool, please merge!

**Comment by juhp** [comment]
Should be all good now, thanks :+1:

**Pull request merged**
