### PR TITLE
Fix #121 Add bindists for GHC 9.2.5

### LINKED ISSUE #121: Provide bindists for GHC 9.2.5
GHC 9.2.5 was [released](https://www.haskell.org/ghc/download_ghc_9_2_5.html) on 7 November 2022.

### PR DESCRIPTION
**Pull request by mpilgrem**
Follows the approach taken to date for GHC 9.2.4.

### CODE REVIEW

**Review by ysangkok — APPROVED** [review]
SHA256's are correct

**Comment by mpilgrem** [comment]
@ysangkok, many thanks for looking at that.

**Comment by juhp** [comment]
Does this need further testing/verification?

It would unblock us for updating Stackage Nightly to 9.2.5. :)

**Comment by mpilgrem** [comment]
@juhp, I could just merge my own pull request, but that feels like marking my own homework for something that is core to Stack. As it is core, I did take some care before raising the PR. In addition to the SHA256, checked by @ysangkok, each entry has a URL, a size in bytes and a SHA1. The source of the latter two are (if my typing is accurate): https://downloads.haskell.org/ghc/9.2.5/.

**Comment by ysangkok** [comment]
I wrote a little Python script that checks the SHA1 and SHA256 too, this also passes:

```
import yaml
import requests

# returns a dictionary with hashes (as bytes) mapped to filenames (without path)
# (according to the sum file given)
def load_sums(filename):
    sha = {}
    with open(filename) as fi:
        for line in fi.readlines():
            hexsha, _, dotslash = line.partition("  ")
            sha[bytes.fromhex(hexsha)] = dotslash[2:-1]
    return sha

sha1 = load_sums('SHA1SUMS')
sha256 = load_sums('SHA256SUMS')

# given a
# - sha_dictionary returned by loads_sums
# - looks up the sha given in sha_key_name, raises if can't be found
# - checks that the url in urlcontentshas (from stack-setup-2) matches the looked up file name
def check_sum(sha_dictionary, sha_key_name, urlcontentshas):
    setupname = sha_dictionary[bytes.fromhex(urlcontentshas[sha_key_name])]
    assert urlcontentshas['url'].endswith(setupname)
    print('passed check', sha_key_name, urlcontentshas['url'])

with open("stack-setup-2.yaml") as fi:
  f = yaml.safe_load(fi.read())

for _arch, versions in f['ghc'].items():
    for version, urlcontentshas in versions.items():
        if version != '9.2.5': continue
        check_sum(sha1, 'sha1', urlcontentshas)
        check_sum(sha256, 'sha256', urlcontentshas)
        serverlength = int(requests.head(urlcontentshas['url']).headers['Content-Length'])
        assert serverlength == urlcontentshas['content-length']
```

outputs

```
passed check sha1 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-i386-deb9-linux.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-i386-deb9-linux.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-x86_64-deb9-linux.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-x86_64-deb9-linux.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-x86_64-fedora27-linux.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-x86_64-fedora27-linux.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-x86_64-apple-darwin.tar.bz2
passed check sha256 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-x86_64-apple-darwin.tar.bz2
passed check sha1 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-aarch64-apple-darwin.tar.bz2
passed check sha256 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-aarch64-apple-darwin.tar.bz2
passed check sha1 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-x86_64-unknown-mingw32-integer-simple.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-x86_64-unknown-mingw32-integer-simple.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-x86_64-unknown-mingw32.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-x86_64-unknown-mingw32.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-aarch64-deb10-linux.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-aarch64-deb10-linux.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-aarch64-deb10-linux.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.2.5/ghc-9.2.5-aarch64-deb10-linux.tar.xz
```

**Comment by mpilgrem** [comment]
@ysangkok, many thanks again!

**Pull request merged**
