### PR TITLE
Add FreeBSD ino64 and non-ino64 bindists of GHC 8.6.4 & 8.6.5.

### PR DESCRIPTION
**Pull request by arrowd**
I'm uploading these right now, so bindists might not be yet available for ~1 hour.

### CODE REVIEW

**Comment by borsboom** [comment]
Happy to add these, but out of curiosity: why not GHC 8.6.5?

**Comment by arrowd** [comment]
Haven't produced these yet. I plan to add them on weekend.

**Comment by arrowd** [comment]
Added 8.6.5 bindists.

**Comment by borsboom** [comment]
Thanks!  It looks like these bindists are on reliable hosting provided by freebsd.org, so I won't mirror them.

**Pull request merged**
