### PR TITLE
Add GHC 8.10.x bindists for FreeBSD aarch64.

### PR DESCRIPTION
**Pull request by MikaelUrankar**

### CODE REVIEW

**Comment by hasufell** [comment]
Who's maintaining these? Since these are unofficial, can you give a bit more info? Are there gpg signatures?

http://distcache.FreeBSD.org/local-distfiles/mikael/stack-bindists isn't browsable. How were the bindists built, on which FreeBSD version?

**Comment by MikaelUrankar** [comment]
I plan to maintain these bindists, I'm a FreeBSD ports committer (mikael@FreeBSD.org)
There are no gpg signatures.
The bindists were built using the FreeBSD ports infrastructure, with a FreeBSD 12.2 version and are compatible with FreeBSD 12.2 up to FreeBSD 14-CURRENT.

**Comment by hasufell** [comment]
I'd be interested to add these to ghcup as well, but I have no idea how to build FreeBSD aarch64 haskell binaries... I mean, neither travis, nor github actions nor gitlab.haskell.org CI support this.

**Comment by arrowd** [comment]
These bindists are quite large in size. I wonder what's the cause for this.

@MikaelUrankar what port options did you use during the build?

**Comment by MikaelUrankar** [comment]
> These bindists are quite large in size. I wonder what's the cause for this.
> 
> @MikaelUrankar what port options did you use during the build?
DOCS=ON
GMP=ON
DYNAMIC=ON
PROFILE=ON

**Comment by arrowd** [comment]
I usually build bindists without DOCS enabled.

**Comment by arrowd** [comment]
What's blocking this?

**Pull request merged**
