### PR TITLE
Fix #118 Add bindists for GHC 9.4.3

### LINKED ISSUE #118: Provide bindists for GHC 9.4.3
GHC 9.4.3 was [released](https://www.haskell.org/ghc/download_ghc_9_4_3.html) on 3 November 2022.

### PR DESCRIPTION
**Pull request by mpilgrem**
Follows the approach taken to date for GHC 9.4.1 and GHC 9.4.2.

### CODE REVIEW

**Comment by ysangkok** [comment]
The script in #122 also passes for this (after adjusting the version):

```
passed check sha1 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-i386-deb9-linux.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-i386-deb9-linux.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-x86_64-deb9-linux.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-x86_64-deb9-linux.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-x86_64-fedora33-linux.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-x86_64-fedora33-linux.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-x86_64-apple-darwin.tar.bz2
passed check sha256 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-x86_64-apple-darwin.tar.bz2
passed check sha1 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-aarch64-apple-darwin.tar.bz2
passed check sha256 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-aarch64-apple-darwin.tar.bz2
passed check sha1 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-x86_64-unknown-mingw32-int_native.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-x86_64-unknown-mingw32-int_native.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-x86_64-unknown-mingw32-int_native.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-x86_64-unknown-mingw32-int_native.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-x86_64-unknown-mingw32.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-x86_64-unknown-mingw32.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-aarch64-deb10-linux.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-aarch64-deb10-linux.tar.xz
passed check sha1 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-aarch64-deb10-linux.tar.xz
passed check sha256 https://downloads.haskell.org/~ghc/9.4.3/ghc-9.4.3-aarch64-deb10-linux.tar.xz
```

**Review by ysangkok — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
I think Debian will work better with Stackage nightly (which is why I approved this). But probably @juhp can speak about the Fedora case

**Comment by juhp** [comment]
Maybe @hasufell has some more insight on this?

**Comment by hasufell** [comment]
> Maybe @hasufell has some more insight on this?
> 
> but I think debian10 would be more portable overall

This is where I disagree. I consider debian not portable. Their downstream patches sometimes cause problems, or the way they build libraries.

https://bugzilla.redhat.com/show_bug.cgi?id=1875587

There was a prominent case where they broke Skype for other distros, because they're even messing with SONAMEs sometimes: https://bugs.gentoo.org/415985

**Comment by mpilgrem** [comment]
I am going to merge this, which follows what Stack originally did for GHC 9.4.1 and GHC 9.4.2, and if something needs fixing (#117 or some other permutation) then it can be applied to all of GHC 9.4.1 to GHC 9.4.3.

**Comment by juhp** [comment]
It might be that centos7 is a better default bindist choice for Linux?
At least I see on RHEL8 that ghcup causes the centos7 bindists of 9.2.5 and 9.4.3 to be installed.

**Comment by juhp** [comment]
So also in the Stackage build server environment we are still using Ubuntu 20.04 and the current default 9.4.3 tarball gives 

```
/var/stackage/.stack/programs/x86_64-linux/ghc-tinfo6-9.4.3/lib/ghc-9.4.3/bin/ghc-pkg: /lib/x86_64-linux-gnu/libc.so.6: version `GLI
BC_2.32' not found (required by /var/stackage/.stack/programs/x86_64-linux/ghc-tinfo6-9.4.3/lib/ghc-9.4.3/bin/../lib/x86_64-linux-gh
c-9.4.3/libHSrts-1.0.2-ghc9.4.3.so)
```

I think it is better to change to centos7, even though that is an older platform than fedora27 (which was roughly rhel/centos 8).

**Comment by juhp** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/22268 is the upstream ticket with related discussion

**Comment by juhp** [comment]
This also broke Stackage CI in github, but we have worked around it by moving the CI action to use Ubuntu 22.04.

(On the Stackage buildserver I worked around it by manually installing the debian10 bindist by hand into our Ubuntu 20.04 build container environment.)

**Pull request merged**
