### PR TITLE
Add GHC 9.2.7 bindists for FreeBSD

### PR DESCRIPTION
**Pull request by arrowd**

### CODE REVIEW

**Comment by mpilgrem** [comment]
@arrowd, many thanks. As of 18 April 2023, there is now a GHC 9.4.5. Could you do the same for that version?

**Comment by arrowd** [comment]
I'm currently fighting Hadrian, as it is required to build GHC 9.4 with bootstrap compilers we currently have. So it will take some time, unfortunately.

**Comment by mpilgrem** [comment]
@arrowd, I hope you are winning your Hadrian battle. FYI, there is now a GHC 9.2.8 and a GHC 9.6.1 and 9.6.2.

**Comment by arrowd** [comment]
Do you still need a bindist for 9.2.7?

**Comment by mpilgrem** [comment]
For completeness, it would be nice. However, nobody has complained that one is not available.

**Pull request merged**
