### PR TITLE
Add 9.2.5 bindists for FreeBSD X86.

### PR DESCRIPTION
**Pull request by arrowd**

### CODE REVIEW

**Comment by arrowd** [comment]
Bump. Can we get this in?

**Comment by mpilgrem** [comment]
@arrowd, can you look at @ZenithalHourlyRate's obsveration above, and advise?

**Comment by arrowd** [comment]
I'm already rebuilding problematic bindist. Indeed, there is something wrong with upload, as the file size is 22Mb.

**Comment by ZenithalHourlyRate** [comment]
> which caused a [sync failure](https://github.com/tuna/tunasync-scripts/blob/cae1194534d6cce0ddea031a2bf318b9aa0261a3/stackage.py#L33) in our side.

We can sync successfully now. Thanks for your fix!

**Comment by mpilgrem** [comment]
@arrowd, do you plan to do something similar for newly-released GHC 9.2.6? https://www.haskell.org/ghc/download_ghc_9_2_6.html

**Comment by arrowd** [comment]
Huh. I somehow missed the announcement. Yes, I will prepare bindists this weekend.

**Pull request merged**
